# app/ia/services/chat/mql_validator_service.py
"""
Validates MongoDB queries generated by the LLM before executing them.
Uses a whitelist of allowed operators and an explicit blocklist for
operators that execute arbitrary code.
"""
from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Operators that execute arbitrary JS/code — always blocked
# ---------------------------------------------------------------------------
_BLOCKED: frozenset[str] = frozenset({
    "$where",
    "$function",
    "$accumulator",
    "$jsReduce",
    "$eval",
})

# ---------------------------------------------------------------------------
# All read-safe MongoDB operators explicitly allowed
# ---------------------------------------------------------------------------
_ALLOWED: frozenset[str] = frozenset({
    # Comparison
    "$eq", "$ne", "$gt", "$gte", "$lt", "$lte", "$in", "$nin",
    # Element / evaluation
    "$exists", "$type", "$regex", "$options", "$mod",
    # Logical
    "$and", "$or", "$nor", "$not",
    # Array
    "$all", "$elemMatch", "$size",
    # Pipeline stages
    "$match", "$group", "$project", "$sort", "$limit", "$skip",
    "$count", "$unwind", "$addFields", "$replaceRoot",
    "$facet", "$bucket", "$sortByCount",
    # Accumulators
    "$sum", "$avg", "$min", "$max", "$first", "$last",
    "$addToSet", "$push",
    # Conditional expressions
    "$cond", "$ifNull", "$switch", "$literal",
    # String expressions
    "$toLower", "$toUpper", "$toString", "$toInt", "$toDouble", "$toDate",
    "$strLenCP", "$substr", "$substrCP", "$concat",
    "$trim", "$ltrim", "$rtrim", "$split", "$indexOfCP",
    # Date expressions
    "$year", "$month", "$dayOfMonth", "$dateToString", "$dateFromString",
    # Arithmetic
    "$multiply", "$divide", "$add", "$subtract", "$abs", "$ceil", "$floor",
    # Array expressions
    "$arrayElemAt", "$concatArrays", "$filter", "$map", "$reduce",
    # Object
    "$mergeObjects", "$objectToArray",
    # Misc
    "$let", "$slice",
})


class MQLValidationError(Exception):
    pass


class MQLValidator:

    def validate(self, query: dict) -> dict:
        """
        Validates a query dict returned by the LLM.
        - Checks that type is 'find' or 'aggregate'.
        - Recursively checks all operators against the whitelist / blocklist.
        Returns the validated query unchanged.
        Raises MQLValidationError on any violation.
        """
        if not isinstance(query, dict):
            raise MQLValidationError("La query debe ser un objeto JSON.")

        query_type = query.get("type")
        if query_type not in ("find", "aggregate"):
            raise MQLValidationError(
                f"Tipo de query no reconocido: '{query_type}'. "
                "Solo se permite 'find' o 'aggregate'."
            )

        if query_type == "find":
            filter_ = query.get("filter", {})
            if not isinstance(filter_, dict):
                raise MQLValidationError("El campo 'filter' debe ser un objeto JSON.")
            self._check_operators(filter_)
            logger.debug(f"✅ MQL find validado | filter={filter_}")

        elif query_type == "aggregate":
            pipeline = query.get("pipeline")
            if not isinstance(pipeline, list) or not pipeline:
                raise MQLValidationError(
                    "El campo 'pipeline' debe ser un array no vacío."
                )
            self._check_operators(pipeline)
            logger.debug(f"✅ MQL aggregate validado | {len(pipeline)} etapas")

        return query

    def _check_operators(self, obj: Any, path: str = "") -> None:
        """Recursively validates all $-prefixed keys in the query structure."""
        if isinstance(obj, dict):
            for key, value in obj.items():
                current = f"{path}.{key}" if path else key
                if key.startswith("$"):
                    if key in _BLOCKED:
                        raise MQLValidationError(
                            f"Operador bloqueado por seguridad: '{key}' en '{current}'."
                        )
                    if key not in _ALLOWED:
                        raise MQLValidationError(
                            f"Operador no permitido: '{key}' en '{current}'."
                        )
                self._check_operators(value, current)
        elif isinstance(obj, list):
            for i, item in enumerate(obj):
                self._check_operators(item, f"{path}[{i}]")


# ---------------------------------------------------------------------------
# Singleton
# ---------------------------------------------------------------------------
_instance: MQLValidator | None = None


def get_mql_validator() -> MQLValidator:
    global _instance
    if _instance is None:
        _instance = MQLValidator()
    return _instance
